package com.mlins.res.setup;

public enum ResUpdateStatus {
    API_KEY_VALIDATION_FAILD,
    API_KEY_ERROR_TYPE_CONNECTION,
    API_KEY_ERROR_TYPE_INVALID_APIKEY,
    API_KEY_NO_RESPONSE,
    OK,
    CAMPUSES_JSON_FAIL,
    CAMPUSES_JSON_OK,
    FAILED;

}
