/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_mlins_gps_aStarData
#define _Included_com_mlins_gps_aStarData
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_mlins_gps_aStarData_findRoute(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
