/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mlins_locator_LocationFinder */

#ifndef _Included_com_mlins_ndk_wrappers_NdkGeneticPathOrderFinder
#define _Included_com_mlins_ndk_wrappers_NdkGeneticPathOrderFinder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkGeneticPathOrderFinder_getPoisOrder(JNIEnv *,
                                                                                          jobject,
                                                                                          jstring,
                                                                                          jint,
                                                                                          jobject,
                                                                                          jobjectArray,
                                                                                          jobjectArray);
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkGeneticPathOrderFinder_getMixedPoisOrder(
        JNIEnv *, jobject, jstring, jint, jobject, jobjectArray, jobjectArray, jobjectArray);
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkGeneticPathOrderFinder_getMultiFacilitiesPoisOrder(
        JNIEnv *, jobject, jstring, jstring, jstring, jint, jobject, jobjectArray, jobjectArray,
        jobjectArray);


#ifdef __cplusplus
}
#endif
#endif
