/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mlins_locator_LocationFinder */

#ifndef _Included_com_mlins_ndk_wrappers_NdkLocationFinder
#define _Included_com_mlins_ndk_wrappers_NdkLocationFinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;IZZ)V
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_load
        (JNIEnv *env, jobject thisObj, jstring facility, jint floor, jboolean isBin);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getFloor
 * Signature: ([Lcom/mlins/wireless/WlBlip;)I
 */
//JNIEXPORT jint JNICALL Java_com_mlins_locator_LocationFinder_getFloor(JNIEnv *, jobject, jobjectArray);

//JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_initParams
//  (JNIEnv *, jobject, jstring appDirPath, jint locationCloseRange,jint k, jfloat pixelsToMeter, jint averageRange, jobjectArray ssidfilter, int floorcount,jstring scantype);


JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_initParams
        (JNIEnv *, jobject, jstring appDirPath, jint locationCloseRange, jint k,
         jfloat pixelsToMeter, jint averageRange, jobjectArray ssidfilter, int floorcount,
         jstring scantype, jfloat closeDevicesThreshold, jfloat closeDeviceWeight,
         jint kTopLevelThr);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    findLocation
 * Signature: (Ljava/util/List;)Lcom/mlins/locator/Location;
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_findLocation
        (JNIEnv *, jobject, jobjectArray, jobject, jboolean);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getLastpt
 * Signature: ()Lcom/mlins/locator/Location;
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getLastpt
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    saveBin
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_saveBin(JNIEnv *env, jobject);


/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    resetLastpt
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_resetLastpt(JNIEnv *env,
                                                                                 jobject);



/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getFileName(JNIEnv *,
                                                                                    jobject);


/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getPointsList
 * Signature: ([Lcom/mlins/locator/FLocation;)V
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getPointsList
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getPointsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getPointsCount
        (JNIEnv *, jobject);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getSsidnames
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getSsidnames
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_mlins_locator_LocationFinder
 * Method:    getSssidnamesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getSssidnamesCount
        (JNIEnv *, jobject);

/** MB Zone Group finder */
JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_initZoneGroupFinder(JNIEnv *,
                                                                                         jobject,
                                                                                         jstring appDirPath);

JNIEXPORT jint JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_findZoneGroup(JNIEnv *,
                                                                                   jobject,
                                                                                   jobjectArray);
/** end MB Zone Group finder */


JNIEXPORT jstring JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_getGroupIdByBlips(JNIEnv *,
                                                                                          jobject,
                                                                                          jobjectArray);


JNIEXPORT void JNICALL Java_com_mlins_ndk_wrappers_NdkLocationFinder_findLocationInsideGeofence(
        JNIEnv *, jobject, jobjectArray, jobject, jfloat, jfloat, jfloat, jfloat);


#ifdef __cplusplus
}
#endif
#endif
